CREATE TABLE ird (
    EVENT_PLACE_ITEM_INDIVIDUAL_NM VARCHAR2(10),
    SET_LIST_ITEM_INDIVIDUAL_NM VARCHAR2(10),
    ACTUAL_MEASUREMENT_RESULT_DIM NUMBER,
    CAPTURED_PASS_IND NUMBER,
    INSPECTIONCOMMENTS VARCHAR2(200),
    CREATED_DT DATE,
    SAMPLENUMBER NUMBER,
    INSPECTION_OCCURRENCE_NAME VARCHAR2(100),
    PRODUCT_PULLED_DT DATE,
    SUPPLIER_PORTAL_USER_ID VARCHAR2(20),
    NETWORK_USER_ID VARCHAR2(20),
    BADGE_NUMBER_ID VARCHAR2(20),
    DEVIATION NUMBER,
    PLANT_ID VARCHAR2(10),
    SITE_NAME VARCHAR2(100),
    INSPECTIONTYPE VARCHAR2(20),
    INSPECTORTYPE VARCHAR2(20),
    EVENT_SAMPLE_QTY NUMBER,
    EVENTTYPE VARCHAR2(20),
    VENDOR VARCHAR2(200),
    PLANTNAME VARCHAR2(100),
    WORKCENTER VARCHAR2(100),
    WORK_ORDER_NBR VARCHAR2(100),
    FEATURE_ID VARCHAR2(20),
    FEATURE_NAME VARCHAR2(100),
    DATUM_TXT VARCHAR2(200),
    SPC VARCHAR2(20),
    CTF VARCHAR2(20),
    NOMINAL_DIM NUMBER,
    LOWER_TOLERANCE_DIM NUMBER,
    UPPER_TOLERANCE_DIM NUMBER,
    ISO_UM_CODE VARCHAR2(20),
    VISUALINSPECTIONTEXT VARCHAR2(200),
    WORKORDERSTATUS VARCHAR2(100),
    WORK_ORDER_CODE VARCHAR2(20),
    INSPECTION_DOCUMENT_NAME VARCHAR2(200),
    INSPECTION_REVISION_CODE VARCHAR2(20),
    INSPECTION_DOCUMENT_DESC VARCHAR2(200),
    TCPN VARCHAR2(100),
    TCPN_REV VARCHAR2(20),
    PART VARCHAR2(100)
    )
 STORAGE ( INITIAL 100k NEXT 100k PCTINCREASE 0 )

/
COMMENT ON TABLE ird IS 'Table ird created'
/
REM @create_ird_table
