select tcpn, tcpn_rev, INSPECTION_DOCUMENT_NAME,INSPECTION_REVISION_CODE,NOMINAL_DIM,LOWER_TOLERANCE_DIM,UPPER_TOLERANCE_DIM, max(created_dt) as Last_DT
from ird
group by tcpn, tcpn_rev, INSPECTION_DOCUMENT_NAME,INSPECTION_REVISION_CODE,NOMINAL_DIM,LOWER_TOLERANCE_DIM,UPPER_TOLERANCE_DIM
;